export const CLINICAL_CONDITIONS = [
  {
    id: "stroke",
    category: "Cerebrovascular",
    symptoms: [
      "Sudden numbness or weakness in face, arm, or leg",
      "Confusion or trouble speaking/understanding speech",
      "Vision problems in one or both eyes",
      "Difficulty walking, dizziness, or loss of balance",
      "Severe headache with no known cause",
    ],
    treatments: [
      "Thrombolytic therapy (tPA) within 4.5 hours",
      "Mechanical thrombectomy for large vessel occlusion",
      "Antiplatelet therapy (aspirin, clopidogrel)",
      "Anticoagulation for cardioembolic stroke",
      "Comprehensive rehabilitation (PT, OT, speech)",
      "Secondary prevention: statins, BP control, lifestyle",
    ],
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&q=80",
  },
  {
    id: "migraine",
    category: "Headache Disorders",
    symptoms: [
      "Moderate to severe throbbing headache (often unilateral)",
      "Nausea and/or vomiting",
      "Photophobia and phonophobia",
      "Aura (visual disturbances, sensory changes)",
      "Worsening with routine physical activity",
    ],
    treatments: [
      "Acute: triptans, NSAIDs, gepants, ditans",
      "Preventive: beta-blockers, anticonvulsants, CGRP mAbs",
      "OnabotulinumtoxinA for chronic migraine",
      "Neuromodulation devices (Cefaly, gammaCore)",
      "Lifestyle: trigger management, sleep hygiene, hydration",
      "Behavioral: CBT, biofeedback, relaxation training",
    ],
    image: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&q=80",
  },
  {
    id: "epilepsy",
    category: "Seizure Disorders",
    symptoms: [
      "Recurrent unprovoked seizures",
      "Focal aware/impaired awareness seizures",
      "Generalized tonic-clonic seizures",
      "Absence seizures (staring spells)",
      "Myoclonic jerks or atonic drops",
      "Postictal confusion or fatigue",
    ],
    treatments: [
      "Antiseizure medications (levetiracetam, lamotrigine, etc.)",
      "Epilepsy surgery for drug-resistant focal epilepsy",
      "Vagus nerve stimulation (VNS)",
      "Responsive neurostimulation (RNS)",
      "Ketogenic diet / modified Atkins diet",
      "Seizure action plans and safety counseling",
    ],
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80",
  },
  {
    id: "parkinsons",
    category: "Movement Disorders",
    symptoms: [
      "Resting tremor (pill-rolling)",
      "Bradykinesia (slowness of movement)",
      "Rigidity (cogwheel or lead-pipe)",
      "Postural instability and gait disturbance",
      "Non-motor: depression, sleep disorders, autonomic dysfunction",
      "Cognitive changes in advanced stages",
    ],
    treatments: [
      "Levodopa/carbidopa (gold standard)",
      "Dopamine agonists (pramipexole, ropinirole)",
      "MAO-B inhibitors (rasagiline, selegiline)",
      "COMT inhibitors (entacapone, opicapone)",
      "Deep brain stimulation (DBS) for motor fluctuations",
      "Physical, occupational, and speech therapy",
    ],
    image: "https://images.unsplash.com/photo-1579684455317-9d2792d6d0f6?w=800&q=80",
  },
  {
    id: "neuropathy",
    category: "Peripheral Nerve Disorders",
    symptoms: [
      "Distal symmetric numbness/tingling (stocking-glove)",
      "Burning, shooting, or electric shock-like pain",
      "Muscle weakness and atrophy",
      "Loss of reflexes (ankle jerks)",
      "Balance impairment and falls",
      "Autonomic symptoms (orthostasis, GI, GU)",
    ],
    treatments: [
      "Glucose optimization for diabetic neuropathy",
      "Pain: gabapentinoids, SNRIs (duloxetine), TCAs",
      "Topical: lidocaine patches, capsaicin 8% patch",
      "IVIG for inflammatory neuropathies (CIDP, GBS)",
      "Physical therapy and assistive devices",
      "Surgical decompression for entrapment neuropathies",
    ],
    image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800&q=80",
  },
  {
    id: "dementia",
    category: "Neurocognitive Disorders",
    symptoms: [
      "Progressive memory impairment (recent > remote)",
      "Executive dysfunction (planning, organizing)",
      "Language difficulties (anomia, comprehension)",
      "Visuospatial deficits",
      "Personality and behavior changes",
      "Impaired activities of daily living (ADLs)",
    ],
    treatments: [
      "Cholinesterase inhibitors (donepezil, rivastigmine, galantamine)",
      "NMDA antagonist (memantine) for moderate-severe AD",
      "Anti-amyloid mAbs (lecanemab, donanemab) for early AD",
      "Non-pharmacologic: cognitive stimulation, exercise",
      "Behavioral management (agitation, psychosis)",
      "Caregiver support, safety planning, advance directives",
    ],
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&q=80",
  },
] as const;
