export const DIAGNOSTIC_TESTS = [
  {
    id: "eeg",
    name: "Electroencephalogram",
    shortName: "EEG",
    duration: "30-60 min",
    desc: "Records electrical activity of the brain to diagnose epilepsy, sleep disorders, and other neurological conditions.",
    prep: "Wash hair without conditioner; avoid caffeine; sleep deprivation may be required.",
    image: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "emg",
    name: "Electromyography",
    shortName: "EMG",
    duration: "30-90 min",
    desc: "Evaluates the health of muscles and the nerve cells that control them to detect neuromuscular disorders.",
    prep: "Avoid lotions or oils on skin; inform doctor if you have a pacemaker or take blood thinners.",
    image: "https://images.unsplash.com/photo-1530497610245-94d3c16cda28?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "evoked",
    name: "Evoked Potentials",
    shortName: "EP",
    duration: "45-60 min",
    desc: "Measures the brain electrical response to visual, auditory, or sensory stimuli to assess nerve pathway function.",
    prep: "Bring glasses or hearing aids if used; wash hair without products; avoid caffeine.",
    image: "https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "cognitive",
    name: "Cognitive Testing",
    shortName: "COG",
    duration: "60-120 min",
    desc: "Comprehensive assessment of memory, attention, language, and executive function for dementia and brain injury evaluation.",
    prep: "Get adequate sleep; bring glasses/hearing aids; take medications as prescribed.",
    image: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?auto=format&fit=crop&w=600&q=80",
  },
] as const;
